[build]
command = "npm install && install --save-dev @types/express && npm install --save-dev @types/cookie-parser && npm install --save-dev @types/morgan && npm install --save-dev @types/jsonfile && npm run build npm "
functions = "functions"
[functions]
external_node_modules = ["express"]
node_bundler = "esbuild"
[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"
